import type { CardDef } from "./types";

const base = {
  hp: 0,
  damage: 0,
  hitSpeed: 1,
  speed: 0,
  range: 0.7,
  radius: 0.42,
  splash: 0,
  count: 1,
  flying: false,
  lifetime: 0,
  deployTime: 0.7,
  spellRadius: 0,
  spellDelay: 0,
  freezeDuration: 0,
  towerDamageRatio: 1,
  sight: 5.5,
} satisfies Partial<CardDef>;

export const CARDS: CardDef[] = [
  {
    ...base,
    id: "sparklets",
    name: "Sparklets",
    subtitle: "Swarm",
    cost: 2,
    kind: "troop",
    role: "melee swarm",
    desc: "Three tiny rift motes that rush the nearest threat.",
    color: "#9be7ff",
    accent: "#5fd2ff",
    rarity: "common",
    hp: 92,
    damage: 48,
    hitSpeed: 0.95,
    speed: 3.35,
    range: 0.55,
    radius: 0.28,
    count: 3,
    sight: 5.2,
  },
  {
    ...base,
    id: "ashblade",
    name: "Ashblade",
    subtitle: "Melee",
    cost: 3,
    kind: "troop",
    role: "melee fighter",
    desc: "A disciplined duelist that carves through single targets.",
    color: "#ffcf70",
    accent: "#ff9d3a",
    rarity: "common",
    hp: 740,
    damage: 145,
    hitSpeed: 1.15,
    speed: 2.35,
    range: 0.65,
    radius: 0.48,
    sight: 5.5,
  },
  {
    ...base,
    id: "boltbow",
    name: "Boltbow",
    subtitle: "Ranged",
    cost: 3,
    kind: "troop",
    role: "ranged",
    desc: "Keeps distance and stitches enemies with aether bolts.",
    color: "#7cffb2",
    accent: "#2ee08a",
    rarity: "rare",
    hp: 280,
    damage: 92,
    hitSpeed: 0.85,
    speed: 2.45,
    range: 5.2,
    radius: 0.4,
    sight: 6.4,
  },
  {
    ...base,
    id: "ironhide",
    name: "Ironhide",
    subtitle: "Tank",
    cost: 5,
    kind: "troop",
    role: "tank",
    desc: "A walking bastion. Slow, stubborn, and built to soak fire.",
    color: "#c9d4e8",
    accent: "#8ea0c4",
    rarity: "epic",
    hp: 1680,
    damage: 128,
    hitSpeed: 1.45,
    speed: 1.55,
    range: 0.75,
    radius: 0.72,
    sight: 5.8,
  },
  {
    ...base,
    id: "cinderpot",
    name: "Cinderpot",
    subtitle: "Splash",
    cost: 4,
    kind: "troop",
    role: "splash",
    desc: "Lobs smoldering pots that burst in a wide splash.",
    color: "#ff8a5b",
    accent: "#ff5a3c",
    rarity: "rare",
    hp: 520,
    damage: 108,
    hitSpeed: 1.55,
    speed: 1.85,
    range: 4.6,
    splash: 1.55,
    radius: 0.5,
    sight: 6.2,
  },
  {
    ...base,
    id: "wardspire",
    name: "Ward Spire",
    subtitle: "Building",
    cost: 5,
    kind: "building",
    role: "defense",
    desc: "Anchors a lane and pummels whatever walks into range.",
    color: "#b08cff",
    accent: "#7b5cff",
    rarity: "epic",
    hp: 980,
    damage: 86,
    hitSpeed: 0.8,
    speed: 0,
    range: 6.2,
    radius: 0.62,
    lifetime: 32,
    sight: 6.6,
    deployTime: 0.85,
  },
  {
    ...base,
    id: "riftburst",
    name: "Riftburst",
    subtitle: "Spell",
    cost: 4,
    kind: "spell",
    role: "area damage",
    desc: "A delayed nova. Shreds clumps; half damage to towers.",
    color: "#ff5ad5",
    accent: "#c81cff",
    rarity: "epic",
    damage: 380,
    spellRadius: 2.45,
    spellDelay: 0.7,
    towerDamageRatio: 0.45,
    deployTime: 0,
  },
  {
    ...base,
    id: "frostbind",
    name: "Frostbind",
    subtitle: "Spell",
    cost: 3,
    kind: "spell",
    role: "freeze",
    desc: "Locks a circle in rime and chips a little health.",
    color: "#8ee7ff",
    accent: "#3ec7ff",
    rarity: "rare",
    damage: 72,
    spellRadius: 2.6,
    spellDelay: 0.2,
    freezeDuration: 3.6,
    towerDamageRatio: 0.4,
    deployTime: 0,
  },
];

export const CARD_MAP: Record<string, CardDef> = Object.fromEntries(
  CARDS.map((c) => [c.id, c]),
);

export const DECK_IDS = CARDS.map((c) => c.id);

export function cardById(id: string): CardDef {
  const c = CARD_MAP[id];
  if (!c) throw new Error(`Unknown card ${id}`);
  return c;
}
